export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const UPDATE_TOKEN = 'UPDATE_TOKEN'
export const UPDATE_IS_DRIVER = false
export const USER_LOCATION = '63.430511, 10.395039'
export const ORDER_ID = -1
export const ORDER_COMPANY_NAME = 'TEST_COMPANY'
export const ORDER_TAXI_NUMBER = 'TEST_TAXI_NUMBER'
export const DEVICE_ID = -1
export const UPDATE_IS_LOADING = true
export const MOB_NUM = 'MOB_NUM'
export const PERMISSION = 'PERMISSION'
